apiVersion: waofed.bitmedia.co.jp/v1beta1
kind: WAOFedConfig
metadata:
  name: default # must be default
spec:
  kubefedNamespace: kube-federation-system
  scheduling:
    selector:
      # any: true # enable the optimizer by default
      hasAnnotation: waofed.bitmedia.co.jp/scheduling
    optimizer:
      method: rr
      # method: wao
      # waoEstimators:
      #   kind-waofed-0:
      #     endpoint: http://localhost:5657
      #   kind-waofed-1:
      #     endpoint: http://localhost:5658
  loadbalancing:
    selector:
      # any: true # enable the optimizer by default
      hasAnnotation: waofed.bitmedia.co.jp/loadbalancing
    optimizer:
      method: rr
      # method: wao
      # waoEstimators:
      #   kind-waofed-0:
      #     endpoint: http://localhost:5657
      #   kind-waofed-1:
      #     endpoint: http://localhost:5658
