//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerSettings) DeepCopyInto(out *LoadBalancerSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerSettings.
func (in *LoadBalancerSettings) DeepCopy() *LoadBalancerSettings {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancingSettings) DeepCopyInto(out *LoadBalancingSettings) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(ResourceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Optimizer != nil {
		in, out := &in.Optimizer, &out.Optimizer
		*out = new(ServiceOptimizerSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancer != nil {
		in, out := &in.LoadBalancer, &out.LoadBalancer
		*out = new(LoadBalancerSettings)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancingSettings.
func (in *LoadBalancingSettings) DeepCopy() *LoadBalancingSettings {
	if in == nil {
		return nil
	}
	out := new(LoadBalancingSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RSPOptimizerSettings) DeepCopyInto(out *RSPOptimizerSettings) {
	*out = *in
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(RSPOptimizerMethod)
		**out = **in
	}
	if in.WAOEstimators != nil {
		in, out := &in.WAOEstimators, &out.WAOEstimators
		*out = make(map[string]*WAOEstimatorSetting, len(*in))
		for key, val := range *in {
			var outVal *WAOEstimatorSetting
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(WAOEstimatorSetting)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RSPOptimizerSettings.
func (in *RSPOptimizerSettings) DeepCopy() *RSPOptimizerSettings {
	if in == nil {
		return nil
	}
	out := new(RSPOptimizerSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSelector) DeepCopyInto(out *ResourceSelector) {
	*out = *in
	if in.Any != nil {
		in, out := &in.Any, &out.Any
		*out = new(bool)
		**out = **in
	}
	if in.HasAnnotation != nil {
		in, out := &in.HasAnnotation, &out.HasAnnotation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSelector.
func (in *ResourceSelector) DeepCopy() *ResourceSelector {
	if in == nil {
		return nil
	}
	out := new(ResourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingSettings) DeepCopyInto(out *SchedulingSettings) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(ResourceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Optimizer != nil {
		in, out := &in.Optimizer, &out.Optimizer
		*out = new(RSPOptimizerSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingSettings.
func (in *SchedulingSettings) DeepCopy() *SchedulingSettings {
	if in == nil {
		return nil
	}
	out := new(SchedulingSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceOptimizerSettings) DeepCopyInto(out *ServiceOptimizerSettings) {
	*out = *in
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(ServiceOptimizerMethod)
		**out = **in
	}
	if in.WAOEstimators != nil {
		in, out := &in.WAOEstimators, &out.WAOEstimators
		*out = make(map[string]*WAOEstimatorSetting, len(*in))
		for key, val := range *in {
			var outVal *WAOEstimatorSetting
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(WAOEstimatorSetting)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceOptimizerSettings.
func (in *ServiceOptimizerSettings) DeepCopy() *ServiceOptimizerSettings {
	if in == nil {
		return nil
	}
	out := new(ServiceOptimizerSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WAOEstimatorSetting) DeepCopyInto(out *WAOEstimatorSetting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WAOEstimatorSetting.
func (in *WAOEstimatorSetting) DeepCopy() *WAOEstimatorSetting {
	if in == nil {
		return nil
	}
	out := new(WAOEstimatorSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WAOFedConfig) DeepCopyInto(out *WAOFedConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WAOFedConfig.
func (in *WAOFedConfig) DeepCopy() *WAOFedConfig {
	if in == nil {
		return nil
	}
	out := new(WAOFedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WAOFedConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WAOFedConfigList) DeepCopyInto(out *WAOFedConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WAOFedConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WAOFedConfigList.
func (in *WAOFedConfigList) DeepCopy() *WAOFedConfigList {
	if in == nil {
		return nil
	}
	out := new(WAOFedConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WAOFedConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WAOFedConfigSpec) DeepCopyInto(out *WAOFedConfigSpec) {
	*out = *in
	if in.Scheduling != nil {
		in, out := &in.Scheduling, &out.Scheduling
		*out = new(SchedulingSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancing != nil {
		in, out := &in.LoadBalancing, &out.LoadBalancing
		*out = new(LoadBalancingSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WAOFedConfigSpec.
func (in *WAOFedConfigSpec) DeepCopy() *WAOFedConfigSpec {
	if in == nil {
		return nil
	}
	out := new(WAOFedConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WAOFedConfigStatus) DeepCopyInto(out *WAOFedConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WAOFedConfigStatus.
func (in *WAOFedConfigStatus) DeepCopy() *WAOFedConfigStatus {
	if in == nil {
		return nil
	}
	out := new(WAOFedConfigStatus)
	in.DeepCopyInto(out)
	return out
}
