name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: "test: run test scripts"
        run: ./test/reset-clusters.sh && ./test/run-basic-tests.sh
      - name: "test: run test scripts (RSPWAO)"
        run: ./test/reset-clusters.sh && ./test/rspoptimizer-wao-setup.sh && ./test/rspoptimizer-wao-run-tests.sh
      - name: "coverage: remove generated files from cover.out"
        run: sed -i -e '/.*_generated.*\.go/d'  cover.out
      - uses: codecov/codecov-action@v3
